Improve schema parser
ronin-co/client pull request #122
Opened 2024-08-21 21:54 UTC by deebov

This is WIP.

2024-08-26 13:53 UTC, deebov commented on bunfig.toml
> +coverageThreshold = 0.995
This will be increased back to 1 shortly.

2024-08-26 13:53 UTC, deebov commented on bunfig.toml
> +coverageThreshold = 0.995
Currently it's unclear to me which lines aren't covered.

2024-08-26 13:57 UTC, colodenn approved these changes

2024-08-26 15:06 UTC, NuroDev requested changes

2024-08-26 15:06 UTC, NuroDev commented on tests/unit/parser.test.ts
> +    expect(() => parseSchemaDefinitions(schema, 'schemas/index.ts')).toThrow(error);
Would a smarter way to do this not to be make a function that throws an error, keep this `.toThrow` to ensure that an error gets thrown and then add a `.catch` or `catch {}` block to check the error message an inside that expect it to match a snapshot?

2024-08-26 15:43 UTC, deebov commented on src/bin/commands/sync.ts
> -      process.exit(1);
Yes this is handled in the `catch` block.

2024-08-26 15:43 UTC, deebov commented on bunfig.toml
> +coverageThreshold = 0.995
I have no clue right now where this is coming from. I don't want to block the release though.

2024-08-26 15:43 UTC, deebov commented on src/bin/parser/errors.ts
> +  return errorMessage;
I guess we could.

2024-08-26 15:43 UTC, deebov commented on src/bin/parser/index.ts
> +const REGISTER_JSON_FIELD_STRUCTURE = process.env.NODE_ENV === 'test';
Nice!

2024-08-26 15:43 UTC, deebov commented on src/bin/parser/index.ts
> + * @param filePath The path to the schema definition file.
Done!

2024-08-26 15:43 UTC, deebov commented on src/bin/parser/index.ts
> +        node.body.statements.forEach((statement) => {
Done!

2024-08-26 15:43 UTC, deebov commented on tests/unit/parser.test.ts
> +    expect(() => parseSchemaDefinitions(schema, 'schemas/index.ts')).toThrow(error);
Great suggestion!

2024-08-26 15:43 UTC, deebov commented on src/bin/parser/index.ts
> +  const registeredSchemas: Record<string, string> = {};
Is there an objective benefit to it than using a mapped object? 

I think we had the same conversation long time ago where we decided it was more of a personal preference.

2024-08-26 15:57 UTC, juriadams requested changes

2024-08-26 15:57 UTC, juriadams commented on bunfig.toml
> +coverageThreshold = 0.995
?

2024-08-27 12:54 UTC, juriadams commented on src/bin/parser/index.ts
> +  const registeredSchemas: Record<string, string> = {};
`Map`s are more performant than objects. Unless you need to serialize them, which is a different topic, let's use `Map`s.

2024-08-28 09:26 UTC, merged