Schemas in code
ronin-co/client pull request #70
Opened 2024-06-20 16:19 UTC by deebov

2024-06-24 09:12 UTC, deebov commented on src/bin/commands/sync.ts
> +    }
Here more logic will be added to handle response of the request.

2024-06-24 09:13 UTC, deebov commented on src/bin/utils/schema.ts
This file is purely about parsing the given schema `.d.ts` file.

2024-06-24 09:14 UTC, deebov commented on src/schema/index.ts
> +// Type that extract only properties keys as union that are Record from given object
```suggestion
```

2024-06-24 09:49 UTC, deebov commented on tsup.config.ts
> +    // Otherwise, you will get an error like:
```suggestion
    // Otherwise, you will get:
```

2024-06-25 07:59 UTC, leo requested changes

2024-06-25 07:59 UTC, leo commented on .husky/pre-commit
> -bunx lint-staged
Why is this being removed? How will Husky run linting now?

2024-06-25 07:59 UTC, leo commented on package.json
> +    "uuid": "10.0.0"
In all other repos, we use [CUID2](https://github.com/paralleldrive/cuid2), which doesn't need an extra types package. Can we use it here too?

2024-06-25 07:59 UTC, leo commented on src/bin/commands/sync.ts
> +    const schemaJson = await parseSchemaDtsFile(schemaDtsFile);
```suggestion
    const schemaJson = await parseSchemaDefinitionFile(schemaDtsFile);
```

This name seems cleaner, IMO. But not blocking.

2024-06-25 07:59 UTC, leo commented on tsup.config.ts
> +    // Error: "Dynamic required of 'fs' is not supported".
```suggestion
    // Error: "Dynamic require of 'fs' is not supported".
```

I assume this is a typo, or...?

2024-06-25 07:59 UTC, leo commented on src/bin/utils/schema.ts
> +import ts from 'typescript';
Shouldn't `typescript` be in `dependencies` instead of `devDependencies`? Otherwise it won't be available when you install the `ronin` package.

2024-06-25 07:59 UTC, leo commented on src/bin/utils/schema.ts
> +                  isNew: true,
Remove `isNew` please, since that property is only used by the `front` client-side. It's not supposed to be stored at all.

Also, defaults for the new `required` property and the `actions` property of "Record" fields are missing.

2024-06-25 13:52 UTC, deebov commented on src/bin/utils/schema.ts
> +import ts from 'typescript';
Makes sense!

2024-06-25 13:54 UTC, deebov commented on tsup.config.ts
> +    // Error: "Dynamic required of 'fs' is not supported".
Great catch!

2024-06-25 13:57 UTC, deebov commented on src/bin/utils/schema.ts
> +                  isNew: true,
It seems like these properties are optional. Should we still provide them?

https://github.com/ronin-co/core/blob/61f4daa09375858688763cd2ff39df57bc799da5/packages/services/validators/schema.ts#L59-L68

2024-06-25 13:58 UTC, deebov commented on .husky/pre-commit
> -bunx lint-staged
This was by mistake. Thanks for pointing it out!

2024-06-25 14:16 UTC, leo commented on src/bin/utils/schema.ts
> +                  isNew: true,
Sounds good to leave them away then.

2024-06-25 14:20 UTC, leo approved these changes

2024-07-02 11:21 UTC, merged