Schemas in code - part 2
ronin-co/client pull request #83
Opened 2024-07-04 19:12 UTC by deebov

2024-07-09 15:45 UTC, deebov commented on src/bin/commands/init.ts
> +    console.log('gitignoreExists', gitignoreExists);
```suggestion
```

2024-07-09 16:25 UTC, deebov commented on src/bin/commands/sync.ts
> +          "You don't have access to any spaces or your CLI session is invalid. Please login again or create a new space and try again.",
```suggestion
          "You don't have access to any space or your CLI session is invalid. Please login again or create a new space and try again.",
```

2024-07-09 17:48 UTC, leo requested changes

2024-07-09 17:48 UTC, leo commented on .eslintrc.json
> +          "dbov"
This is not mentioned elsewhere in the diff. Let's remove it?

2024-07-09 17:48 UTC, leo commented on .gitignore
> +# Environment variables
Why would the `client` repo have `.ronin` metadata or environment variables?

Both of those things are for apps, and the `client` repo is not an app.

2024-07-09 17:48 UTC, leo commented on scripts/cjs-shim.ts
> +// @ts-expect-error The `path` will anyway be imported by the injected script
```suggestion
// @ts-expect-error The `path` module will anyway be imported by the injected script
```

2024-07-09 17:48 UTC, leo commented on src/bin/commands/init.ts
> +    // Add .ronin to .gitignore if .gitignore exists but doesn't contain .ronin.
```suggestion
    // Add `.ronin` to `.gitignore` if `.gitignore` exists but doesn't contain `.ronin`.
```

2024-07-09 17:48 UTC, leo commented on src/bin/utils/sync.ts
> +  }
Can you also perform a check for `res.ok`? Meaning if the response is not "ok", we need to error.

2024-07-09 17:48 UTC, leo commented on src/bin/utils/sync.ts
> + */
```suggestion
/**
 * Fetch the existing schemas for the configured space.
 *
 * @param token Either an app token or a session token.
 * @param space The ID of the space to fetch schemas for.
 *
 * @returns The schemas of the provided space.
 */
```

I get the intention, but we don't normally capitalize those two.

2024-07-09 17:48 UTC, leo commented on src/bin/utils/sync.ts
> +  }
Can you also perform a check for `res.ok`? Meaning if the response is not "ok", we need to error.

2024-07-09 17:48 UTC, leo commented on src/bin/utils/sync.ts
> + */
```suggestion
/**
 * Replace the IDs of fields in the local schema with the IDs
 * of the existing fields in the remote schema.
 *
 * @param local Local schema definitions.
 * @param remote Existing remote schema definitions.
 *
 * @returns Updated local schema definitions.
 */
```

"ID's" means something is owned by the IDs. For example: "The ID's car", meaning a car owned by an ID. If you just want to refer to them, you need to use "IDs", just like you use "cars" and not "car's".

2024-07-09 17:48 UTC, leo commented on src/bin/utils/schema.ts
> + * Parses the schema definition file and returns an array of Schema objects.
```suggestion
 * Parses the schema definition file and returns an array of `Schema` objects.
```

Code should be in backticks.

2024-07-09 17:48 UTC, leo commented on src/bin/utils/schema.ts
> + * @returns A promise that resolves to an array of Schema objects.
```suggestion
 * @returns A promise that resolves to an array of `Schema` objects.
```

Code should be in backticks.

2024-07-09 17:48 UTC, leo commented on src/bin/utils/schema.ts
> +      `The following Schemas were used as a reference but weren't included in the Schemas interface: ${Array.from(missingSchemas).join(', ')}.\nPlease include them in the Schemas interface or remove
```suggestion
      `The following schemas were used as a reference but weren't included in the `Schemas` interface: ${Array.from(missingSchemas).join(', ')}.\nPlease include them in the `Schemas` interface or remove their references.`,
```

We don't normally capitalize "schemas". When referencing the respective object in code, it must use backticks.

2024-07-09 17:48 UTC, leo commented on src/bin/commands/sync.ts
> +  }
A spinner can't fail with an error message that is not actionable for developers.

Developers don't know what a session token is and neither do they need to know that.

This case should be impossible, right? Meaning the surrounding command function would not even be called if one of them wouldn't be available.

To account for that, you could use a `throw new Error` statement to add an exception.

2024-07-09 17:48 UTC, leo commented on src/bin/commands/sync.ts
> +          "You don't have access to any spaces or your CLI session is invalid. Please login again or create a new space and try again.",
Can we tell them how to log in?

E.g. "using `ronin login`".

2024-07-09 20:41 UTC, deebov commented on .gitignore
> +# Environment variables
I added this while testing the CLI. I guess others might do this as well.

2024-07-09 20:42 UTC, deebov commented on src/bin/commands/sync.ts
> +  }
Yes, this would be impossible! Added this to only satisfy TS.

2024-07-09 20:47 UTC, deebov commented on src/bin/commands/sync.ts
> +          "You don't have access to any spaces or your CLI session is invalid. Please login again or create a new space and try again.",
Good idea! Done!

2024-07-09 20:49 UTC, deebov commented on src/bin/utils/sync.ts
> +  }
Done!

2024-07-09 20:51 UTC, deebov commented on src/bin/utils/sync.ts
> + */
Thanks for the explanation! I'm aware of what it should mean. Just eslint was complaining so I used that.

2024-07-10 07:52 UTC, leo commented on .gitignore
> +# Environment variables
Could you elaborate? From what I can see, people shouldn't test the CLI in the `client` repo.

They should run `bun link` and then run `ronin` either from their terminal in a different directory, or put it into the `package.json` file of an app.

The `client` repo doesn't contain an app, so why would someone run `ronin` here...?

2024-07-10 08:05 UTC, leo requested changes

2024-07-10 08:05 UTC, leo commented on src/bin/utils/sync.ts
> +    const res = await fetch(`https://ronin.supply/-/ronin/schemas?data-selector=${space}`, {
FYI: App tokens already contain the space ID.

You likely need the space ID in addition, because of session tokens, but mentioning it regardless, in case it helps you elsewhere in the codebase.

2024-07-10 08:05 UTC, leo commented on src/bin/utils/sync.ts
> + */
Sure, but that doesn't make it any more correct. Sometimes ESLint doesn't work as expected, in which case we need to ignore certain words (like you did).

2024-07-10 13:02 UTC, deebov commented on .gitignore
> +# Environment variables
I needed in order to test the sync command quickly while developing it. I don't see how adding a couple of lines in `.gitignore` could be a blocker for this PR, considering if I as a core maintainer of this repo needed it.

2024-07-10 13:03 UTC, deebov commented on .eslintrc.json
> +          "Ds"
That doesn't work for eslint. eslint sees only `Ds` as a wrong word.

2024-07-10 13:04 UTC, deebov commented on src/bin/utils/sync.ts
> +    const res = await fetch(`https://ronin.supply/-/ronin/schemas?data-selector=${space}`, {
I'm aware, this space ID is the locally stored space ID.

2024-07-10 13:23 UTC, deebov commented on .gitignore
> +.env
```suggestion

```

2024-07-10 13:24 UTC, leo approved these changes

2024-07-10 16:01 UTC, leo approved these changes

2024-07-10 16:06 UTC, merged